### ISSUE TITLE
create-gist.sh: line 65: /usr/bin/curl: Argument list too long

### ISSUE THREAD

**Issue by pauldotknopf** [ceremcem/create-gist#2]
```curl``` version:
```
curl 7.56.1 (x86_64-pc-linux-gnu) libcurl/7.56.1 OpenSSL/1.1.0g zlib/1.2.11 libpsl/0.18.0 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.27.0
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by ceremcem** [comment]
What is the size of stdout/file you are trying to send to? Can you provide an example file for reproduction of the issue?

**Comment by lhanson** [comment]
I've experienced the same problem, my file is 4403595 bytes, available [here](https://gist.github.com/lhanson/109757daf150f077cad082e6ac89a4f0).

**Comment by ceremcem** [comment]
This is now fixed by using file upload method ([here](https://github.com/ceremcem/create-gist/blob/cbe57f9d03d5c80848c3da5129192aa7ac12368e/create-gist.sh#L69)). If you encounter any further difficulties, feel free to reopen the issue. Thanks for the report and the test case.

**Comment by lhanson** [comment]
Awesome, thanks so much for the fast turnaround!
