### ISSUE TITLE
feature request: OTP

### ISSUE THREAD

**Issue by magnetophon** [ceremcem/create-gist#6]
Would be nice to be able to use this with OTP enabled.
ATM I get:
```
----- ERROR -----
{
  "message": "Must specify two-factor authentication OTP code.",
  "documentation_url": "https://developer.github.com/v3/auth#working-with-two-factor-authentication"
}
```

**Comment by ceremcem** [comment]
OAuth token decision is made very weakly (if it is 40 character-long, then it is assumed to be a token). Please inform any difficulties if you encounter.

**Comment by magnetophon** [comment]
That went totally over my head, sorry.

**Comment by ceremcem** [comment]
Current usage is as follows: 

`create_gist.sh ceremcem` 

or 

`create-gist.sh 6f4d671b83e39ca306e3d36d8da21a8e517547cd`

As you can see, first parameter is used as username or token. This decision (whether you passed a username or a token) is made automatically based on character length of the parameter. If it is 40 characters long, it is considered as a token. 

I choose this approach (automatic decision) for ease of use but I think it became an overhead already :) What I meant is that, if Github creates tokens less or greater than 40-characters-long in the future, the code will be broken. As I don't think this will happen in near future, it will work for a long time. 

Anyway, if you encounter any problems with "token authentication", please let me know.

**Comment by magnetophon** [comment]
Ah, thanks!
