### ISSUE TITLE
Password authentication will depreciate soon

### ISSUE THREAD

**Issue by redyoshi49q** [ceremcem/create-gist#7]
Upon using this script, I got an automated email from Github:

> Hi @redyoshi49q,
> 
> On August 1st, 2020 at 07:09 (UTC) you used a password to access an endpoint through the GitHub API using curl/7.58.0:
> 
> [https://api.github.com/gists](https://api.github.com/gists)
> 
> Basic authentication using a password to the API is deprecated and will soon no longer work. Visit [https://developer.github.com/changes/2020-02-14-deprecating-password-auth/](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/) for more information around suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

The linked page suggests that the password authentication measure used by this script will break in mid-November (though token authentication will presumably still work fine).

**Comment by ceremcem** [comment]
I think nobody uses the password authentication anyway, so we may simply remove this support.
